#!/usr/bin/env bash
set -euo pipefail

# Deployment script for AltaVidaTours on Ubuntu 22.04 (Hostinger VPS)
# - Uses PM2 (single instance)
# - Uses nginx to serve static assets and proxy to Node
# - Uses Next.js standalone output and disables server image optimization (reduces CPU)
#
# IMPORTANT: Review APP_DIR, DOMAIN, PM2_NAME and PORT before running.

# ---- CONFIG - ADJUST BEFORE RUNNING ----
APP_DIR="/var/www/altavidatours"      # <-- path to your app
DOMAIN="altavidatours.com"            # <-- domain or IP
ADMIN_EMAIL="admin@altavidatours.com" # <-- email for Let's Encrypt registration
SERVICE_NAME="altavida"               # <-- name for systemd service (and default pm2 name)
PORT=3003                               # <-- port to run the app on (you specified 3003)
NGINX_SITE_NAME="altavida"            # used for /etc/nginx/sites-available/<name>

# Choose run method: set to "true" to run via systemd, or "false" to use pm2.
USE_SYSTEMD=true

# PM2 options (will be written but not used when USE_SYSTEMD=true). These include
# memory restart thresholds and node args to limit heap size to reduce VPS memory usage.
PM2_MAX_MEMORY="400M"
PM2_NODE_ARGS="--max-old-space-size=256"
# ----------------------------------------

echo "Deployment script starting..."
echo "APP_DIR=$APP_DIR"
echo "DOMAIN=$DOMAIN"
echo "SERVICE_NAME=$SERVICE_NAME"
echo "PORT=$PORT"

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run this script as root (sudo)."
  exit 1
fi

# Basic checks
if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not found. Install nginx and re-run. (sudo apt update && sudo apt install -y nginx)"
  exit 1
fi

# If we're using pm2 later, ensure it's installed; if using systemd, it's optional
if [ "$USE_SYSTEMD" = "false" ] && ! command -v pm2 >/dev/null 2>&1; then
  echo "pm2 not found. Install it globally (npm i -g pm2) and re-run, or set USE_SYSTEMD=true to use systemd."
  exit 1
fi

if [ ! -d "$APP_DIR" ]; then
  echo "App directory not found: $APP_DIR"
  exit 1
fi

cd "$APP_DIR"

# 1) Back up existing next.config.js (if any) and write recommended config
if [ -f "next.config.js" ]; then
  ts=$(date +%Y%m%d_%H%M%S)
  echo "Backing up existing next.config.js -> next.config.js.bak.$ts"
  cp -a next.config.js next.config.js.bak.$ts
fi

cat > next.config.js <<'NEXTCONF'
/** Generated by deploy script - sets standalone output and disables image optimization at runtime */
const nextConfig = {
  output: 'standalone',
  images: {
    unoptimized: true
  },
};
module.exports = nextConfig;
NEXTCONF

echo "Wrote next.config.js (standalone + images.unoptimized = true)."

# 2) Install dependencies (use npm ci for clean install)
echo "Installing dependencies (this may take a while)..."
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

# 3) Build the Next app (production build)
echo "Running npm run build..."
npm run build

# 4) Create PM2 ecosystem file (with resource limits) and/or a systemd unit
# We'll generate both configs; the script will start the selected runner (systemd by default).

echo "Writing PM2 ecosystem file (with memory limits)"
cat > ecosystem.config.js <<EOF
module.exports = {
  apps: [
    {
      name: "${SERVICE_NAME}",
      script: "./.next/standalone/server.js",
      cwd: "${APP_DIR}",
      instances: 1,
      exec_mode: 'fork',
      node_args: "${PM2_NODE_ARGS}",
      max_memory_restart: "${PM2_MAX_MEMORY}",
      env: {
        NODE_ENV: "production",
        PORT: ${PORT}
      }
    }
  ]
}
EOF

if [ "$USE_SYSTEMD" = true ]; then
  # Create a systemd service unit to run the standalone server
  SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
  echo "Creating systemd unit: $SERVICE_FILE"
  cat > "$SERVICE_FILE" <<SYSTEMD
[Unit]
Description=AltaVida Tours Next.js standalone server
After=network.target

[Service]
Type=simple
WorkingDirectory=${APP_DIR}/.next/standalone
Environment=NODE_ENV=production
Environment=PORT=${PORT}
ExecStart=/usr/bin/node ${APP_DIR}/.next/standalone/server.js
Restart=always
RestartSec=5
LimitNOFILE=65536
# Optionally set a memory limit (commented) - requires systemd slice/cgroups tuning
# MemoryMax=512M

[Install]
WantedBy=multi-user.target
SYSTEMD

  echo "Reloading systemd and starting ${SERVICE_NAME} service"
  systemctl daemon-reload
  systemctl enable --now ${SERVICE_NAME}
  systemctl restart ${SERVICE_NAME}
else
  echo "Using pm2 to start the app (single instance, memory limit applied)."
  pm2 describe "${SERVICE_NAME}" >/dev/null 2>&1 && pm2 delete "${SERVICE_NAME}" || true
  pm2 start ecosystem.config.js --only "${SERVICE_NAME}" --env production
  pm2 save
fi

# 5) Nginx configuration (serve static assets directly and proxy to node)
NGINX_AVAILABLE="/etc/nginx/sites-available/${NGINX_SITE_NAME}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${NGINX_SITE_NAME}"

# Backup existing site config (if any)
if [ -f "$NGINX_AVAILABLE" ]; then
  ts=$(date +%Y%m%d_%H%M%S)
  cp -a "$NGINX_AVAILABLE" "${NGINX_AVAILABLE}.bak.${ts}"
fi

cat > "$NGINX_AVAILABLE" <<NGINXCONF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Serve Next static files directly
    location ^~ /_next/static/ {
        alias ${APP_DIR}/.next/static/;
        access_log off;
        expires max;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Proxy any other _next requests to next server
    location ^~ /_next/ {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Serve public/ directly
    location ^~ /static/ {
      alias ${APP_DIR}/public/;
      access_log off;
      expires max;
    }
    location = /favicon.ico {
      alias ${APP_DIR}/public/favicon.ico;
      access_log off;
      expires max;
    }

    # Proxy everything else to Next standalone server
    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINXCONF

# Enable site
ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"


echo "Testing nginx configuration..."
nginx -t

echo "Reloading nginx..."
systemctl reload nginx

# 6) Obtain TLS certificate via Certbot (Let's Encrypt) and update nginx
if ! command -v certbot >/dev/null 2>&1; then
  echo "Installing certbot..."
  apt update
  apt install -y certbot python3-certbot-nginx
fi

echo "Requesting TLS certificate for ${DOMAIN} using certbot (nginx plugin)"
# Non-interactive obtain and install; requires DNS to point to server and port 80 open
certbot --nginx -d ${DOMAIN} --non-interactive --agree-tos -m ${ADMIN_EMAIL} || {
  echo "certbot failed to obtain certificate. You can try running certbot manually later."
}

echo "Deployment finished."
if command -v pm2 >/dev/null 2>&1; then
  echo "PM2 processes:"
  pm2 ls
  echo "You can view logs with: pm2 logs ${SERVICE_NAME}"
fi

echo "If running under systemd, check service status with: systemctl status ${SERVICE_NAME}"
echo "Done."
